#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KnightTime.Android.View.Resource", IsApplication=true)]

namespace KnightTime.Android.View
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040002
			public const int pref_monitorModes = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int pref_smartAlarmTypes_entries = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int pref_smartAlarmTypes_values = 2130968577;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050004
			public const int aqua = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int blue = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int darkblue = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int gold = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int light_yellow = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060008
			public const int alarm_clock_large_size = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int alarm_clock_medium_size = 2131099657;
			
			// aapt resource value: 0x7f06000e
			public const int button_large_width = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int button_medium_width = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int graph_large_height = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int graph_large_width = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int graph_medium_height = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int graph_medium_width = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int layout_large_marginBottom = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int layout_large_marginSides = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int layout_large_marginTop = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int layout_medium_marginBottom = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int layout_medium_marginSides = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int layout_medium_marginTop = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int radialView_large = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int radialView_medium = 2131099654;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int abSettingsButton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int blue_button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Checkmark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int container = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int error = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int gold_button = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_alarm = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_action_alarm_2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_action_bulb = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_action_calculator = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_action_cancel = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_action_clock = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_action_export = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_action_google_play = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_action_happy = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_action_heart = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_action_knight = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_action_line_chart = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_action_location_2 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_action_minus = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_action_music_2 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_action_news = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_action_phone = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_action_pinterest = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_action_plane = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_action_playback_play = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_action_playback_stop = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_action_reload = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_action_rocket = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_action_sad = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_action_share = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_action_stamp = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_action_stumbleupon = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_action_sun = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_action_tick = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_action_turn_left = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_action_turn_right = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_action_volume_mute = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_action_volume_up = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int knighttimelauncher = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int KnightTimeLogo_Dark = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int KnightTimeSplash_Dark = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int monoandroidsplash = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int results_item_bg = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int results_item_bg_pressed = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int results_item_blue_bg = 2130837549;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b001d
			public const int AbortMonitorButton = 2131427357;
			
			// aapt resource value: 0x7f0b0000
			public const int AlertTitle = 2131427328;
			
			// aapt resource value: 0x7f0b0019
			public const int BaseStationConnectionStateImageView = 2131427353;
			
			// aapt resource value: 0x7f0b001a
			public const int BaseStationLabel = 2131427354;
			
			// aapt resource value: 0x7f0b0003
			public const int Chart = 2131427331;
			
			// aapt resource value: 0x7f0b0013
			public const int ConnectionInfoContainer = 2131427347;
			
			// aapt resource value: 0x7f0b0014
			public const int ConnectionsLabel = 2131427348;
			
			// aapt resource value: 0x7f0b001e
			public const int DigitalClockGraphsFragment = 2131427358;
			
			// aapt resource value: 0x7f0b0001
			public const int Dismiss = 2131427329;
			
			// aapt resource value: 0x7f0b002a
			public const int GraphContainer = 2131427370;
			
			// aapt resource value: 0x7f0b001c
			public const int GraphContainerMonitorActivity = 2131427356;
			
			// aapt resource value: 0x7f0b0002
			public const int Graphs = 2131427330;
			
			// aapt resource value: 0x7f0b0008
			public const int GuestButton = 2131427336;
			
			// aapt resource value: 0x7f0b0007
			public const int LinearLayoutButtons = 2131427335;
			
			// aapt resource value: 0x7f0b0005
			public const int LinearLayoutImage = 2131427333;
			
			// aapt resource value: 0x7f0b0009
			public const int LoginButton = 2131427337;
			
			// aapt resource value: 0x7f0b000a
			public const int Main = 2131427338;
			
			// aapt resource value: 0x7f0b0028
			public const int MainMenuListView = 2131427368;
			
			// aapt resource value: 0x7f0b000d
			public const int MainMenu_Caption = 2131427341;
			
			// aapt resource value: 0x7f0b000c
			public const int MainMenu_Name = 2131427340;
			
			// aapt resource value: 0x7f0b000b
			public const int MainMenu_icon = 2131427339;
			
			// aapt resource value: 0x7f0b0017
			public const int MaskConnectionStateImageView = 2131427351;
			
			// aapt resource value: 0x7f0b0018
			public const int MaskLabel = 2131427352;
			
			// aapt resource value: 0x7f0b001b
			public const int RadialPollProgress = 2131427355;
			
			// aapt resource value: 0x7f0b0023
			public const int ResultsListView = 2131427363;
			
			// aapt resource value: 0x7f0b0026
			public const int StartMonitor = 2131427366;
			
			// aapt resource value: 0x7f0b0029
			public const int StartStopButton = 2131427369;
			
			// aapt resource value: 0x7f0b0015
			public const int WristConnectionStateImageView = 2131427349;
			
			// aapt resource value: 0x7f0b0016
			public const int WristLabel = 2131427350;
			
			// aapt resource value: 0x7f0b0011
			public const int btOkButtonMathGame = 2131427345;
			
			// aapt resource value: 0x7f0b0027
			public const int digitalClock1 = 2131427367;
			
			// aapt resource value: 0x7f0b0010
			public const int etMathGameAnswer = 2131427344;
			
			// aapt resource value: 0x7f0b002d
			public const int export_as_csv = 2131427373;
			
			// aapt resource value: 0x7f0b0006
			public const int imageView1 = 2131427334;
			
			// aapt resource value: 0x7f0b002c
			public const int logout = 2131427372;
			
			// aapt resource value: 0x7f0b0020
			public const int result_icon_image_view = 2131427360;
			
			// aapt resource value: 0x7f0b002e
			public const int share = 2131427374;
			
			// aapt resource value: 0x7f0b0012
			public const int tableRow1 = 2131427346;
			
			// aapt resource value: 0x7f0b002b
			public const int test = 2131427371;
			
			// aapt resource value: 0x7f0b0025
			public const int textItem = 2131427365;
			
			// aapt resource value: 0x7f0b001f
			public const int thumbnail = 2131427359;
			
			// aapt resource value: 0x7f0b0021
			public const int tvDayDate = 2131427361;
			
			// aapt resource value: 0x7f0b0022
			public const int tvDescription = 2131427362;
			
			// aapt resource value: 0x7f0b000f
			public const int tvMathProblem = 2131427343;
			
			// aapt resource value: 0x7f0b000e
			public const int tvMathProblem_Title = 2131427342;
			
			// aapt resource value: 0x7f0b0024
			public const int tvNoResults = 2131427364;
			
			// aapt resource value: 0x7f0b0004
			public const int tvNoText = 2131427332;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int MaxReplyMsgCount = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AlarmAlert = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Graphs = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LogIn = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MainMenu_Item = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MathGame = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Monitor = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MonitorPaneFragment = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Results_Item = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ResultsFragment = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Settings = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Simple_Spinner_Item = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int StartMonitor = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Summary = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int TextViewItem = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int ActionItems = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int SummaryActionItems = 2131361793;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080001
			public const int ApplicationName = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int DefaultNone = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int Hello = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int ModeMessageLabel = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int SetTimeMessageLabel = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int StartMonitorText = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int StopMonitorText = 2131230725;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090007
			public const int Container = 2131296263;
			
			// aapt resource value: 0x7f09000a
			public const int Mono_Android_Theme_Splash = 2131296266;
			
			// aapt resource value: 0x7f090005
			public const int MyActionBar = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int MyActionBar_Text = 2131296262;
			
			// aapt resource value: 0x7f090004
			public const int Theme_Activity = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int Theme_LogIn = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int Theme_Settings = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int Theme_Splash = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int Theme_SplashEmpty = 2131296257;
			
			// aapt resource value: 0x7f090008
			public const int button_text = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int button_text2 = 2131296265;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
